## 1.Numpy
- Python에서 수학적인 계산(행렬, 백터, 차원)을 편하게 할 수 있도록 돕는 라이브러리!

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# 1차원 배열
arr1 = np.array([1, 2, 3])
arr1
type(arr1)
arr1.shape # 1행 3열
arr1.ndim # 1차원

1

In [4]:
# 2차원 배열
arr2 = np.array([[1, 2, 3], [1, 2, 3]])

arr2
type(arr2)
arr2.shape # 2행 3열
arr2.ndim # 2차원

2

In [5]:
# ndarry 데이터 타입

arr3 = ['1', '2', '3']

arr3 = np.array(arr3)
arr3 = arr3.astype(np.int64)
arr3.dtype
# arr3.shape

dtype('int64')

In [6]:
# ndraay 생성

arr = np.arange(10)

print(arr > 5)  # boolean indexing
print(arr[arr > 5])

[False False False False False False  True  True  True  True]
[6 7 8 9]


In [ ]:
a = np.zeros((3,2))
b = np.ones((3, 2))
c = np.ones((10, 10))
print(a)
print(b)
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# reshape
arr = np.arange(10)

arr.reshape(2, 5)
arr.reshape(5, 2)
arr.reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
# indexing & slicing
arr[0]
arr[:5]
arr[5:]

array([5, 6, 7, 8, 9])

# numpy 문제

# Q1. 2차원 배열에서 각 행의 평균을 계산하는 코드를 작성하세요

``` python
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
```

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

# axis=0(열), axis=1(행), axis=2(채널)
np.mean(arr, axis=1)

array([2., 5., 8.])

# Q2. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요
``` python
arr = np.array([1,2,3,4,5,6])
```

In [ ]:
arr = np.array([1,2,3,4,5,6])

# for문 이용하기
def 짝수():
    nums = [ i  for i in arr if i%2 == 0 ]
    return nums
짝수()

# np 이용하기

# np.arange(시작숫자, 끝숫자, 증가범위) => (0, 6, 2) =>  0<=배열<6
even_indexes = np.arange(0, arr.size, 2) # [0, 2, 4]
print(arr[even_indexes]) # arr의 0, 2, 4 번째 인덱스를 찾아서 프린트해줌

[1 3 5]


# Q3. 2차원 배열의 주 대각선 상에 있는 원소들을 출력하는 코드를 작성하세요
``` python
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
```

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr.shape

# diag 주대각 \ 행렬 출력
np.diag(arr)

# 슬라이싱을 이용한 역대각 / 행렬 출력
np.diag(arr[::-1])[::-1]

print(arr)
print('주대각', np.diag(arr))
print('역대각', np.diag(arr[::-1])[::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
주대각 [1 5 9]
역대각 [3 5 7]


# Q4. 2차원 배열에서 각 열의 표준 편차를 계산하는 코드를 작성하세요
``` python
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
```

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# 표준편차 => np.std()

np.std(arr, axis=0)

array([2.44948974, 2.44948974, 2.44948974])

# Q5. 2차원 배열에서 각 행의 최댓값과 그 인덱스를 출력하는 코드를 작성하세요
``` python
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
```

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.amax(arr, axis=1)

array([3, 6, 9])

# Q6. 1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하세요
```python
arr = np.array([1,2,3,4,5])
```

In [7]:
arr = np.array([1,2,3,4,5])
np.median(arr)

3.0

# Q7. 1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요
``` python
arr = np.array([1,4,6,3,9,2,7,8])
```

In [11]:
# Boolean indexing
arr = np.array([1,4,6,3,9,2,7,8])

print(arr >= 5)
print(arr[arr >= 5])

[False False  True False  True False  True  True]
[6 9 7 8]


# Q8. 1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성하세요
```python
arr = np.array([1,3,5,2,4,6,3,5,7])
```

In [14]:
arr = np.array([1,3,5,2,4,6,3,5,7])
print(np.where((arr == 3) | (arr == 5)))
print(arr[np.where((arr == 3) | (arr == 5))])

(array([1, 2, 6, 7]),)
[3 5 3 5]


# **gaussian_process**

(**머신러닝에서 많이 사용하는 알고리즘**)

[링크](https://github.com/scikit-learn/scikit-learn/blob/9aaed498795f68e5956ea762fef9c440ca9eb239/sklearn/gaussian_process/kernels.py)